[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_ENV = "production"
PORT = { default = "3000" }

[service]
name = "discord-secret-room-bot"
